# Generated by Django 4.0 on 2022-08-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('date', models.DateField()),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('date', models.DateField()),
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('OverallQual', models.IntegerField()),
                ('CarCap', models.IntegerField()),
                ('Garagecar', models.IntegerField()),
                ('YearBuilt', models.IntegerField()),
                ('Livingarea', models.IntegerField()),
                ('TotalBsmt', models.IntegerField()),
                ('RemodificationDate', models.IntegerField()),
                ('MasonaryType', models.IntegerField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
