# Generated by Django 4.0 on 2022-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmyhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
