# Generated by Django 4.0 on 2022-08-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmyhome', '0002_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
